name: "Run tests using pytest"

on: [workflow_dispatch, push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install pip modules
        run: pip install tox

      - name: Run tests
        run: tox test

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report-html
          path: htmlcov/

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report-xml
          path: coverage.xml